### ISSUE TITLE
Ch.8 Confidence.T

### ISSUE THREAD

**Issue by DaniKeselman** [DaniKeselman/Team-3--Mens-baseball#1]
Hey @esthephania  could you complete the confidence.T on excel?

https://spartansut-my.sharepoint.com/:x:/g/personal/dani_keselman_spartans_ut_edu/ERWfYnK8GbdBjt_mdGPsxZABHIXvTg4_rBz_hCVvwHZxrQ?e=ujcvgg

**Comment by esthephania** [comment]
Will do! thanks

**Comment by DaniKeselman** [comment]
Just saw the work looks good!
