### ISSUE TITLE
Ch. 8 Confidence.Norm

### ISSUE THREAD

**Issue by DaniKeselman** [DaniKeselman/Team-3--Mens-baseball#2]
Hey @madisonfichera could you complete the confidence.norm on excel. 

my.sharepoint.com/:x:/g/personal/dani_keselman_spartans_ut_edu/ERWfYnK8GbdBjt_mdGPsxZABHIXvTg4_rBz_hCVvwHZxrQ?e=CoAfdN

**Comment by madisonfichera** [comment]
Yea of course!

**Comment by DaniKeselman** [comment]
Thank you! Just paste it on Powerpoint when done. 

https://spartansut-my.sharepoint.com/:p:/g/personal/dani_keselman_spartans_ut_edu/EVNFfzxIpEtBqZyY8u-HGXABQ4B4tyRRD9iqi2GuKyfGZw?e=dANMNB
