### ISSUE TITLE
Ch. 9 Null Hypothesis for Known or Unknown Population

### ISSUE THREAD

**Issue by DaniKeselman** [DaniKeselman/Team-3--Mens-baseball#5]
Hey @mayanorthrup  can you complete the Null hypothesis on excel?

https://spartansut-my.sharepoint.com/:x:/g/personal/dani_keselman_spartans_ut_edu/ERWfYnK8GbdBjt_mdGPsxZABHIXvTg4_rBz_hCVvwHZxrQ?e=8o6clG

**Comment by mayanorthrup** [comment]
Hey Dani I will complete this right now!

**Comment by DaniKeselman** [comment]
Thank you, just upload it on the PowerPoint when done!

https://spartansut-my.sharepoint.com/:p:/g/personal/dani_keselman_spartans_ut_edu/EVNFfzxIpEtBqZyY8u-HGXABQ4B4tyRRD9iqi2GuKyfGZw?e=dANMNB
