### ISSUE TITLE
Ch. 14 Linear Regression Prediction

### ISSUE THREAD

**Issue by DaniKeselman** [DaniKeselman/Team-3--Mens-baseball#7]
Hey @ccsampair can you complete the Linear Regression Prediction on excel?

https://spartansut-my.sharepoint.com/:x:/g/personal/dani_keselman_spartans_ut_edu/ERWfYnK8GbdBjt_mdGPsxZABHIXvTg4_rBz_hCVvwHZxrQ?e=UJxLRP

**Comment by ccsampair** [comment]
yeah

**Comment by DaniKeselman** [comment]
Sounds good thank you!
